### ISSUE TITLE
AssertionError on UCIS3 data set

### ISSUE THREAD

**Issue by DanielArndt** [DanielArndt/flowtbag-old#6]
18:59:34;INFO:: Took 17.140000 s to process 500000 packets :: flowtbag.py:147
18:59:34;INFO:: Current size of the flowtbag: 203717 :: flowtbag.py:149
18:59:35;INFO:: Cleaned up 19580 idle flows :: flowtbag.py:102
18:59:52;INFO:: Processed 63500000 packets. Timestamp 1276201778.717592 :: flowt
bag.py:145
18:59:52;INFO:: Took 17.700000 s to process 500000 packets :: flowtbag.py:147
18:59:52;INFO:: Current size of the flowtbag: 195959 :: flowtbag.py:149
Traceback (most recent call last):
  File "./flowtbag.py", line 245, in <module>
    Flowtbag(args.capture_file)
  File "./flowtbag.py", line 73, in **init**
    pcap_reader.loop(-1,self.callback)
  File "/usr/lib64/python2.7/site-packages/pcap.py", line 93, in loop
    def loop(_args): return _pcap.pcapObject_loop(_args)
  File "./flowtbag.py", line 151, in callback
    self.cleanup_active(ts)
  File "./flowtbag.py", line 99, in cleanup_active
    flow.export()
  File "/home/darndt/workspace/flowtbag/src/flowtbag/flow.py", line 608, in expo
rt  
    print self
  File "/home/darndt/workspace/flowtbag/src/flowtbag/flow.py", line 341, in **st
r** 
    assert (self.a_duration > 0)
AssertionError

**Comment by DanielArndt** [comment]
20:38:54;ERROR:: Error printing flow 1360442 which starts with packet 57862039 :: flow.py:612
20:38:54;ERROR:: First packet: 1276201168 Last: 1276201168 :: flow.py:614
